apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-cluster
  region: us-east-1

managedNodeGroups:
  - name: spot
    instanceType: m5.large
    desiredCapacity: 2
    spot: true

# eksctl create cluster --config-file=eks.yaml
# eksctl delete cluster --config-file=eks.yaml
# https://github.com/eksctl-io/eksctl/blob/main/examples